FROM node:8-alpine

LABEL Author Zenobius Jiricek <airtonix@users.noreply.github.com>

WORKDIR /app
COPY ./package.json .
COPY ./package-lock.json .
RUN npm install

COPY ./src ./src
CMD [ "node ./index.js" ]
